services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm-workspaces
    ports:
      - 3843:3000
      - 443:443
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor:rootlesskit
    environment:
      - KASM_PORT=443
    networks:
      - "cloudflared"
    volumes:
      - "${VOLUME_LOCATION}/kasm_workspaces/data:/opt"
      - "${VOLUME_LOCATION}/kasm_workspaces/profiles:/profiles"

networks:
  cloudflared:
    external: true
    name: "cloudflared"